/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalImprintRouteImport } from './routes/legal/imprint'
import { Route as LegalCookiesRouteImport } from './routes/legal/cookies'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout/success'
import { Route as CheckoutCancelRouteImport } from './routes/checkout/cancel'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiShopProfileRouteImport } from './routes/api/shop/profile'
import { Route as ApiShopPortalRouteImport } from './routes/api/shop/portal'
import { Route as ApiShopEntitlementsRouteImport } from './routes/api/shop/entitlements'
import { Route as ApiShopCheckoutRouteImport } from './routes/api/shop/checkout'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalImprintRoute = LegalImprintRouteImport.update({
  id: '/legal/imprint',
  path: '/legal/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCancelRoute = CheckoutCancelRouteImport.update({
  id: '/checkout/cancel',
  path: '/checkout/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopProfileRoute = ApiShopProfileRouteImport.update({
  id: '/api/shop/profile',
  path: '/api/shop/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopPortalRoute = ApiShopPortalRouteImport.update({
  id: '/api/shop/portal',
  path: '/api/shop/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopEntitlementsRoute = ApiShopEntitlementsRouteImport.update({
  id: '/api/shop/entitlements',
  path: '/api/shop/entitlements',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopCheckoutRoute = ApiShopCheckoutRouteImport.update({
  id: '/api/shop/checkout',
  path: '/api/shop/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/imprint': typeof LegalImprintRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/shop/checkout': typeof ApiShopCheckoutRoute
  '/api/shop/entitlements': typeof ApiShopEntitlementsRoute
  '/api/shop/portal': typeof ApiShopPortalRoute
  '/api/shop/profile': typeof ApiShopProfileRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/imprint': typeof LegalImprintRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/shop/checkout': typeof ApiShopCheckoutRoute
  '/api/shop/entitlements': typeof ApiShopEntitlementsRoute
  '/api/shop/portal': typeof ApiShopPortalRoute
  '/api/shop/profile': typeof ApiShopProfileRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/imprint': typeof LegalImprintRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/shop/checkout': typeof ApiShopCheckoutRoute
  '/api/shop/entitlements': typeof ApiShopEntitlementsRoute
  '/api/shop/portal': typeof ApiShopPortalRoute
  '/api/shop/profile': typeof ApiShopProfileRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/legal/cookies'
    | '/legal/imprint'
    | '/legal/privacy'
    | '/legal/terms'
    | '/api/auth/$'
    | '/api/shop/checkout'
    | '/api/shop/entitlements'
    | '/api/shop/portal'
    | '/api/shop/profile'
    | '/api/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/legal/cookies'
    | '/legal/imprint'
    | '/legal/privacy'
    | '/legal/terms'
    | '/api/auth/$'
    | '/api/shop/checkout'
    | '/api/shop/entitlements'
    | '/api/shop/portal'
    | '/api/shop/profile'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/legal/cookies'
    | '/legal/imprint'
    | '/legal/privacy'
    | '/legal/terms'
    | '/api/auth/$'
    | '/api/shop/checkout'
    | '/api/shop/entitlements'
    | '/api/shop/portal'
    | '/api/shop/profile'
    | '/api/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutCancelRoute: typeof CheckoutCancelRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalImprintRoute: typeof LegalImprintRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiShopCheckoutRoute: typeof ApiShopCheckoutRoute
  ApiShopEntitlementsRoute: typeof ApiShopEntitlementsRoute
  ApiShopPortalRoute: typeof ApiShopPortalRoute
  ApiShopProfileRoute: typeof ApiShopProfileRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/imprint': {
      id: '/legal/imprint'
      path: '/legal/imprint'
      fullPath: '/legal/imprint'
      preLoaderRoute: typeof LegalImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/cancel': {
      id: '/checkout/cancel'
      path: '/checkout/cancel'
      fullPath: '/checkout/cancel'
      preLoaderRoute: typeof CheckoutCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shop/profile': {
      id: '/api/shop/profile'
      path: '/api/shop/profile'
      fullPath: '/api/shop/profile'
      preLoaderRoute: typeof ApiShopProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shop/portal': {
      id: '/api/shop/portal'
      path: '/api/shop/portal'
      fullPath: '/api/shop/portal'
      preLoaderRoute: typeof ApiShopPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shop/entitlements': {
      id: '/api/shop/entitlements'
      path: '/api/shop/entitlements'
      fullPath: '/api/shop/entitlements'
      preLoaderRoute: typeof ApiShopEntitlementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shop/checkout': {
      id: '/api/shop/checkout'
      path: '/api/shop/checkout'
      fullPath: '/api/shop/checkout'
      preLoaderRoute: typeof ApiShopCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutCancelRoute: CheckoutCancelRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalImprintRoute: LegalImprintRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiShopCheckoutRoute: ApiShopCheckoutRoute,
  ApiShopEntitlementsRoute: ApiShopEntitlementsRoute,
  ApiShopPortalRoute: ApiShopPortalRoute,
  ApiShopProfileRoute: ApiShopProfileRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
